/** @type {import('tailwindcss').Config} */
// Design tokens from Stitch (Material Design 3 expressive palette). Moved
// from an inline `<script>tailwind.config = {...}</script>` block in
// App.razor so the static CLI build can apply them at compile time. The
// previous Play-CDN approach evaluated this config at runtime in the
// browser, which produced inconsistent rendering vs the production build
// because Play CDN's JIT doesn't see Razor files the same way the CLI does.
module.exports = {
  darkMode: 'class',
  content: [
    './Components/**/*.razor',
    './Components/**/*.razor.cs',
    './Components/**/*.cs',
    './Components/**/*.cshtml',
    './Styles/**/*.css',
    '../CharM.Web/Components/**/*.razor',
    '../CharM.Web/Components/**/*.razor.cs',
  ],
  safelist: [
    // PowerCardModel.cs builds these classes dynamically. Tailwind Play CDN
    // used to see them after Blazor rendered; the static CLI needs them listed.
    'bg-success-container/40',
    'bg-error-container/10',
    'bg-primary',
    'bg-amber-100',
    'bg-amber-200',
    'bg-amber-300',
    'bg-sky-100',
    'bg-sky-200',
    'bg-surface-container-high',
    'bg-on-success-container/10',
    'bg-error/10',
    'bg-white/20',
    'bg-outline/10',
    'border-outline-variant/10',
    'border-outline-variant/20',
    'border-amber-300',
    'border-error',
    'border-white/40',
    'border-outline/40',
    'text-on-success-container',
    'text-on-success-container/70',
    'text-error',
    'text-error/70',
    'text-on-primary',
    'text-amber-900',
    'text-amber-950',
    'text-sky-900',
    'text-on-tertiary-container',
    'text-outline',
    'text-outline/70',
    'text-white/70',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#e5e2e1',
        'on-tertiary-container': '#5d5c57',
        'inverse-surface': '#0c0f0f',
        'on-primary-container': '#525151',
        'on-surface': '#2d3435',
        'secondary': '#5f5f5f',
        'primary-dim': '#535252',
        'on-secondary': '#fbf8f8',
        'surface-container-low': '#f2f4f4',
        'secondary-fixed': '#e4e2e1',
        'secondary-fixed-dim': '#d6d4d3',
        'error-container': '#fe8983',
        'on-primary-fixed-variant': '#5c5b5b',
        'surface-container-highest': '#dde4e5',
        'on-tertiary-fixed-variant': '#676661',
        'surface-container-high': '#e4e9ea',
        'tertiary-fixed': '#f6f3ec',
        'on-primary': '#faf7f6',
        'on-primary-fixed': '#403f3f',
        'outline-variant': '#acb3b4',
        'on-secondary-fixed': '#3f3f3f',
        'surface-dim': '#d3dbdd',
        'surface-bright': '#f9f9f9',
        'outline': '#757c7d',
        'surface-container': '#ebeeef',
        'error-dim': '#4e0309',
        'on-error': '#fff7f6',
        'primary-fixed-dim': '#d6d4d3',
        'on-secondary-container': '#525252',
        'on-error-container': '#752121',
        'surface-variant': '#dde4e5',
        'tertiary': '#605f5a',
        'on-tertiary': '#fcf9f2',
        'surface-tint': '#5f5e5e',
        'tertiary-fixed-dim': '#e8e5de',
        'background': '#f9f9f9',
        'on-surface-variant': '#596061',
        'error': '#9f403d',
        'secondary-dim': '#535353',
        'surface': '#f9f9f9',
        'inverse-on-surface': '#9c9d9d',
        'primary': '#5f5e5e',
        'on-secondary-fixed-variant': '#5c5b5b',
        'tertiary-dim': '#54534e',
        'primary-container': '#e5e2e1',
        'secondary-container': '#e4e2e1',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#f6f3ec',
        'on-background': '#2d3435',
        'inverse-primary': '#ffffff',
        'on-tertiary-fixed': '#4a4a45',
        'success-container': '#dcfce7',
        'on-success-container': '#166534',
      },
      fontFamily: {
        // Order matters: the first available font wins. We bundle the
        // primary face as WOFF2 under wwwroot/fonts/; the fallbacks
        // ensure something readable shows during the brief FOIT/FOUT
        // before the WOFF2 loads (and on devices that can't render it).
        'headline': ['"Noto Serif"', 'Georgia', 'Cambria', 'serif'],
        'body': ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        'label': ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
