#!/usr/bin/env python3
"""Generate weapons.yaml + the weapon half of proficiencies.yaml from Basic.html.
Verbatim weapon stats (name, hands, proficiency bonus, damage die, cost, weight,
properties, group). Armor proficiency elements/bundle are preserved. Run from repo root."""
import re, html

src = open("Basic.html", encoding="utf-8").read()
tables = re.findall(r"<table.*?</table>", src, re.S)
def cells(row): return [html.unescape(re.sub(r"<[^>]+>"," ",c)).strip() for c in re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", row, re.S)]
def collapse(s): return " ".join(s.split())

def parse(table, ranged):
    rows=[cells(r) for r in re.findall(r"<tr[^>]*>(.*?)</tr>", table, re.S)]
    out=[]; tier=None
    for r in rows:
        nz=[c for c in r if c.strip()]
        if not nz: continue
        if nz[0] in ("Type","Name"): continue
        if len(nz)==1:  # tier subheader: "Simple Weapons" / "Simple" / ...
            tier = nz[0].split()[0]  # Simple/Martial/Exotic
            continue
        if ranged:
            name,hands,prof,dmg,rng,cost,wt,props,grp = (r+[""]*9)[:9]
        else:
            name,hands,prof,dmg,cost,wt,props,grp = (r+[""]*8)[:8]; rng=""
        out.append(dict(name=collapse(name),hands=collapse(hands),prof=collapse(prof),
                        dmg=collapse(dmg),rng=collapse(rng),cost=collapse(cost),wt=collapse(wt),
                        props=collapse(props),grp=collapse(grp),
                        cat=f"{tier} {'Ranged' if ranged else 'Melee'}", tier=tier,
                        kind="Ranged" if ranged else "Melee"))
    return out

melee = parse(tables[11], False)
ranged = parse(tables[12], True)
weapons = melee + ranged

def slug(s):
    return re.sub(r"_+","_", re.sub(r"[^A-Z0-9]","_", s.upper())).strip("_")

def q(s): return '"' + s.replace('"','\\"') + '"'

# ---- weapons.yaml ----
w=["# Weapons (Orcus Basic Rules, Basic.html) — generated by tools/weapons_from_basic.py.",
   "# One Weapon element per row of the Melee/Ranged weapon tables; stats copied",
   "# verbatim (damage die, proficiency bonus, properties, group). Regenerate; do",
   "# not hand-edit.",""]
seen=set()
for x in weapons:
    wid="ORCUS_WEAPON_"+slug(x["name"])
    if wid in seen: wid+="_2"
    seen.add(wid)
    slot = "Two Hands" if x["hands"]=="2" else "Main Hand"
    w.append(f"- id: {wid}")
    w.append(f"  name: {q(x['name'])}")
    w.append(f"  type: Weapon")
    w.append(f'  source: "Orcus Original"')
    w.append(f"  categories: [{x['kind']}, {x['tier']}]")
    w.append(f"  fields:")
    w.append(f'    "Weapon Category": {q(x["cat"])}')
    w.append(f'    "Item Slot": {q(slot)}')
    w.append(f'    Hands: {q(x["hands"])}')
    w.append(f'    Damage: {q(x["dmg"])}')
    w.append(f'    "Proficiency Bonus": {q(x["prof"].lstrip("+"))}')
    if x["rng"]: w.append(f'    Range: {q(x["rng"])}')
    w.append(f'    Group: {q(x["grp"])}')
    if x["cost"]: w.append(f'    Cost: {q(x["cost"]+" gp")}')
    if x["wt"]: w.append(f'    Weight: {q(x["wt"]+" lb")}')
    if x["props"]: w.append(f'    Properties: {q(x["props"])}')
    w.append("")
open("content/orcus/equipment/weapons.yaml","w").write("\n".join(w))

# ---- proficiencies.yaml (weapons regenerated, armor preserved) ----
p=["# Weapon & armor proficiencies. Weapon part generated from Basic.html by",
   "# tools/weapons_from_basic.py; per-weapon Proficiency elements grouped into the",
   "# category bundles the classes grant. Armor proficiencies are hand-maintained.",""]
p.append("# === Weapon proficiency elements ==============================================")
for x in weapons:
    pid="ORCUS_WPROF_"+slug(x["name"])
    p.append(f'- {{ id: {pid}, name: "Weapon Proficiency ({x["name"]})", type: Proficiency, source: "Orcus Original" }}')
p.append("")
# bundles by category
bundles={"Simple Melee":"ORCUS_PROFGRANT_SIMPLE_MELEE","Martial Melee":"ORCUS_PROFGRANT_MARTIAL_MELEE",
 "Exotic Melee":"ORCUS_PROFGRANT_EXOTIC_MELEE","Simple Ranged":"ORCUS_PROFGRANT_SIMPLE_RANGED",
 "Martial Ranged":"ORCUS_PROFGRANT_MARTIAL_RANGED","Exotic Ranged":"ORCUS_PROFGRANT_EXOTIC_RANGED"}
names={"Simple Melee":"Simple Melee","Martial Melee":"Martial Melee","Exotic Melee":"Exotic Melee",
 "Simple Ranged":"Simple Ranged","Martial Ranged":"Martial Ranged","Exotic Ranged":"Exotic Ranged"}
p.append("# === Category grant bundles ===================================================")
for cat,bid in bundles.items():
    members=[x for x in weapons if x["cat"]==cat]
    if not members: continue
    p.append(f"- id: {bid}")
    p.append(f'  name: "{names[cat]} Weapon Proficiency"')
    p.append(f"  type: Grants")
    p.append(f'  source: "Orcus Original"')
    p.append(f"  rules:")
    for x in members:
        p.append(f'    - {{ grant: ORCUS_WPROF_{slug(x["name"])}, type: Proficiency }}')
    p.append("")
# armor proficiency elements + light bundle (preserved)
p.append("# === Armor proficiency elements ===============================================")
for a in ["Cloth","Leather","Hide","Chainmail","Scale","Plate","Light Shield","Heavy Shield"]:
    p.append(f'- {{ id: ORCUS_APROF_{slug(a)}, name: "Armor Proficiency ({a})", type: Proficiency, source: "Orcus Original" }}')
p.append("")
p.append("- id: ORCUS_PROFGRANT_ARMOR_LIGHT")
p.append('  name: Light Armor Proficiency')
p.append("  type: Grants")
p.append('  source: "Orcus Original"')
p.append("  rules:")
for a in ["CLOTH","LEATHER","HIDE"]:
    p.append(f"    - {{ grant: ORCUS_APROF_{a}, type: Proficiency }}")
p.append("")
open("content/orcus/equipment/proficiencies.yaml","w").write("\n".join(p))
print(f"weapons: {len(weapons)} ({len(melee)} melee, {len(ranged)} ranged)")
