#!/usr/bin/env python3
"""Generate weapons.yaml + the weapon half of proficiencies.yaml from Basic.html.
Verbatim weapon stats (name, hands, proficiency bonus, damage die, cost, weight,
properties, group). Armor proficiency elements/bundle are preserved. Run from repo root."""
import re, html

src = open("Basic.html", encoding="utf-8").read()
tables = re.findall(r"<table.*?</table>", src, re.S)
def cells(row): return [html.unescape(re.sub(r"<[^>]+>"," ",c)).strip() for c in re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", row, re.S)]
def collapse(s): return " ".join(s.split())

def parse(table, ranged):
    rows=[cells(r) for r in re.findall(r"<tr[^>]*>(.*?)</tr>", table, re.S)]
    out=[]; tier=None
    for r in rows:
        nz=[c for c in r if c.strip()]
        if not nz: continue
        if nz[0] in ("Type","Name"): continue
        if len(nz)==1:  # tier subheader: "Simple Weapons" / "Simple" / ...
            tier = nz[0].split()[0]  # Simple/Martial/Exotic
            continue
        if ranged:
            name,hands,prof,dmg,rng,cost,wt,props,grp = (r+[""]*9)[:9]
        else:
            name,hands,prof,dmg,cost,wt,props,grp = (r+[""]*8)[:8]; rng=""
        out.append(dict(name=collapse(name),hands=collapse(hands),prof=collapse(prof),
                        dmg=collapse(dmg),rng=collapse(rng),cost=collapse(cost),wt=collapse(wt),
                        props=collapse(props),grp=collapse(grp),
                        cat=f"{tier} {'Ranged' if ranged else 'Melee'}", tier=tier,
                        kind="Ranged" if ranged else "Melee"))
    return out

melee = parse(tables[11], False)
ranged = parse(tables[12], True)
weapons = melee + ranged

def slug(s):
    return re.sub(r"_+","_", re.sub(r"[^A-Z0-9]","_", s.upper())).strip("_")

def q(s): return '"' + s.replace('"','\\"') + '"'

# ---- weapons.yaml ----
w=["# Weapons (Orcus Basic Rules, Basic.html) — generated by tools/weapons_from_basic.py.",
   "# One Weapon element per row of the Melee/Ranged weapon tables; stats copied",
   "# verbatim (damage die, proficiency bonus, properties, group). Regenerate; do",
   "# not hand-edit.",""]
seen=set()
for x in weapons:
    wid="ORCUS_WEAPON_"+slug(x["name"])
    if wid in seen: wid+="_2"
    seen.add(wid)
    slot = "Two Hands" if x["hands"]=="2" else "Main Hand"
    w.append(f"- id: {wid}")
    w.append(f"  name: {q(x['name'])}")
    w.append(f"  type: Weapon")
    w.append(f'  source: "Orcus Basic"')
    w.append(f"  categories: [{x['kind']}, {x['tier']}]")
    w.append(f"  fields:")
    w.append(f'    "Weapon Category": {q(x["cat"])}')
    w.append(f'    "Item Slot": {q(slot)}')
    w.append(f'    Hands: {q(x["hands"])}')
    w.append(f'    Damage: {q(x["dmg"])}')
    w.append(f'    "Proficiency Bonus": {q(x["prof"].lstrip("+"))}')
    if x["rng"]: w.append(f'    Range: {q(x["rng"])}')
    w.append(f'    Group: {q(x["grp"])}')
    if x["cost"]: w.append(f'    Cost: {q(x["cost"]+" gp")}')
    if x["wt"]: w.append(f'    Weight: {q(x["wt"]+" lb")}')
    if x["props"]: w.append(f'    Properties: {q(x["props"])}')
    w.append("")
open("content/orcus/equipment/weapons.yaml","w").write("\n".join(w))

# ---- proficiencies.yaml (weapons regenerated, armor preserved) ----
p=["# Weapon & armor proficiencies. Weapon part generated from Basic.html by",
   "# tools/weapons_from_basic.py; per-weapon Proficiency elements grouped into the",
   "# category bundles the classes grant. Armor proficiencies are hand-maintained.",""]
p.append("# === Weapon proficiency elements ==============================================")
for x in weapons:
    pid="ORCUS_WPROF_"+slug(x["name"])
    p.append(f'- {{ id: {pid}, name: "Weapon Proficiency ({x["name"]})", type: Proficiency, source: "Orcus Basic", categories: [ORCUS_WEAPON_PROFS] }}')
p.append("")
# bundles by category
bundles={"Simple Melee":"ORCUS_PROFGRANT_SIMPLE_MELEE","Martial Melee":"ORCUS_PROFGRANT_MARTIAL_MELEE",
 "Exotic Melee":"ORCUS_PROFGRANT_EXOTIC_MELEE","Simple Ranged":"ORCUS_PROFGRANT_SIMPLE_RANGED",
 "Martial Ranged":"ORCUS_PROFGRANT_MARTIAL_RANGED","Exotic Ranged":"ORCUS_PROFGRANT_EXOTIC_RANGED"}
names={"Simple Melee":"Simple Melee","Martial Melee":"Martial Melee","Exotic Melee":"Exotic Melee",
 "Simple Ranged":"Simple Ranged","Martial Ranged":"Martial Ranged","Exotic Ranged":"Exotic Ranged"}
p.append("# === Category grant bundles ===================================================")
for cat,bid in bundles.items():
    members=[x for x in weapons if x["cat"]==cat]
    if not members: continue
    p.append(f"- id: {bid}")
    p.append(f'  name: "{names[cat]} Weapon Proficiency"')
    p.append(f"  type: Grants")
    p.append(f'  source: "Orcus Basic"')
    p.append(f"  rules:")
    for x in members:
        p.append(f'    - {{ grant: ORCUS_WPROF_{slug(x["name"])}, type: Proficiency }}')
    p.append("")
# armor proficiency elements + light bundle (preserved)
p.append("# === Armor proficiency elements ===============================================")
for a in ["Cloth","Leather","Hide","Chainmail","Scale","Plate","Light Shield","Heavy Shield"]:
    # Selectable categories scope the Armor/Shield Proficiency feat menus. Cloth
    # is universal (everyone is proficient), so it is not an offerable choice.
    cat = "ORCUS_SHIELD_PROFS" if "Shield" in a else ("" if a == "Cloth" else "ORCUS_ARMOR_PROFS")
    catpart = f", categories: [{cat}]" if cat else ""
    p.append(f'- {{ id: ORCUS_APROF_{slug(a)}, name: "Armor Proficiency ({a})", type: Proficiency, source: "Orcus Original"{catpart} }}')
p.append("")
p.append("- id: ORCUS_PROFGRANT_ARMOR_LIGHT")
p.append('  name: Light Armor Proficiency')
p.append("  type: Grants")
p.append('  source: "Orcus Original"')
p.append("  rules:")
for a in ["CLOTH","LEATHER","HIDE"]:
    p.append(f"    - {{ grant: ORCUS_APROF_{a}, type: Proficiency }}")
p.append("")
open("content/orcus/equipment/proficiencies.yaml","w").write("\n".join(p))

# ---- weapon-focus.yaml (Weapon Focus / Specialization options, per weapon group) ----
# One option per atomic weapon group (the groups actually present on the weapons).
# The engine applies a stat named "<Group> group:attack" / ":damage" only when the
# power's weapon belongs to <Group>; the +1 -> +2 (L11) -> +3 (L21) scaling uses
# level-gated Feat-typed statadds (highest wins, so the tier supersedes, not stacks).
groups = sorted({g.strip() for x in weapons for g in x["grp"].split(",") if g.strip()})
f=["# Weapon Focus / Weapon Specialization options — generated by",
   "# tools/weapons_from_basic.py from the weapon Group data. The matching feats",
   "# pick one of these; do not hand-edit, regenerate.",""]
def focus_block(group, kind, scope):
    gid=slug(group)
    typ=f"Weapon {kind}"
    cat=f"ORCUS_WEAPON_{'FOCUS' if kind=='Focus' else 'SPEC'}"
    pid=f"ORCUS_WEAPON{'FOCUS' if kind=='Focus' else 'SPEC'}_{gid}"
    stat=f"{group} group:{scope}"
    f.append(f"- id: {pid}")
    f.append(f'  name: "{typ} ({group})"')
    f.append(f"  type: {typ}")
    f.append(f'  source: "Orcus Original"')
    f.append(f"  categories: [{cat}]")
    f.append(f"  rules:")
    f.append(f'    - {{ statadd: "{stat}", value: 1, bonusType: Feat }}')
    f.append(f'    - {{ statadd: "{stat}", value: 2, bonusType: Feat, level: 11 }}')
    f.append(f'    - {{ statadd: "{stat}", value: 3, bonusType: Feat, level: 21 }}')
    f.append("")
f.append("# === Weapon Focus (+attack) ===================================================")
for g in groups: focus_block(g,"Focus","attack")
f.append("# === Weapon Specialization (+damage) ==========================================")
for g in groups: focus_block(g,"Specialization","damage")
open("content/orcus/equipment/weapon-focus.yaml","w").write("\n".join(f))

print(f"weapons: {len(weapons)} ({len(melee)} melee, {len(ranged)} ranged); weapon groups: {len(groups)}")
