using System.Text;
using System.Text.RegularExpressions;
using System.Web;

namespace CharM.Orcus.Import;

/// <summary>
/// Deterministic parser + generator + verbatim gate for the Advanced Options
/// "# Arts" chapter (practices and incantations — the learn-then-perform
/// subsystem). Each detailed art entry (an H3 with a "Level N &lt;subtype&gt;
/// Practice|Incantation (Skill)" descriptor) becomes a <c>Ritual</c> element so
/// it plugs straight into the engine's existing rituals/practices machinery:
/// the app lists every Ritual element as a learnable/purchasable art, and the
/// character sheet groups them under "Rituals, Alchemy &amp; Martial Practices".
///
/// Structured fields (Level / Skill / Category / Art Type / Market Price (Cost
/// to Learn) / Component Cost / Time / Duration) are parsed; the rules body
/// (including the "&lt;Skill&gt; check:" rider) is the verbatim Description.
/// Acquisition gating is by the source rules (be trained in the associated skill
/// for a practice; the Gated Arts variant adds the Incantation Caster / Practical
/// Arts feats) and is recorded via the Skill field rather than auto-enforced —
/// the rituals/practices catalogue does not run prerequisites.
/// </summary>
public static class ArtsGen
{
    static readonly Regex H1 = new(@"^#\s+(.+?)\s*$", RegexOptions.Compiled);
    static readonly Regex AnyHeader = new(@"^#{1,3}\s", RegexOptions.Compiled);
    static readonly Regex H3 = new(@"^###\s+(.+?)\s*$", RegexOptions.Compiled);
    static readonly Regex Descriptor = new(
        @"^Level\s+(?<lvl>\d+)\s+(?<sub>.+?)\s+(?<art>Practice|Incantation)\s*\((?<skill>.+?)\)\s*$",
        RegexOptions.Compiled);
    static readonly Regex Field = new(@"^\*\*(?<lbl>[^*:]+?):\*\*\s*(?<val>.*)$", RegexOptions.Compiled);

    public static int Generate(string book, string outPath)
    {
        var lines = File.ReadAllLines(book);
        int secStart = -1, secEnd = lines.Length;
        for (int i = 0; i < lines.Length; i++)
        {
            var m = H1.Match(lines[i]);
            if (!m.Success) continue;
            string h = HttpUtility.HtmlDecode(m.Groups[1].Value).Trim();
            if (secStart < 0) { if (h.Equals("Arts", StringComparison.OrdinalIgnoreCase)) secStart = i; }
            else { secEnd = i; break; }
        }
        if (secStart < 0) throw new Exception("'# Arts' section not found");

        // Every header line bounds an entry block; an art is an H3 whose block
        // begins with a "Level N … (Skill)" descriptor.
        var headers = new List<int>();
        for (int i = secStart + 1; i < secEnd; i++) if (AnyHeader.IsMatch(lines[i])) headers.Add(i);

        var sb = new StringBuilder();
        sb.AppendLine("# Arts (Orcus Advanced Options, # Arts) — practices & incantations, the");
        sb.AppendLine("# learn-then-perform subsystem. Generated by tools/CharM.Orcus.Import");
        sb.AppendLine("# (generate-arts). Each is a Ritual element so it plugs into the engine's");
        sb.AppendLine("# existing rituals/practices machinery (listed as a learnable/purchasable art,");
        sb.AppendLine("# grouped on the sheet under \"Rituals, Alchemy & Martial Practices\"). Level/");
        sb.AppendLine("# Skill/Category/Art Type/Market Price (Cost to Learn)/Component Cost/Time/");
        sb.AppendLine("# Duration are parsed; the rules body is the verbatim Description, round-trip");
        sb.AppendLine("# checked. Gating (skill training; the Gated Arts feats) is recorded via the");
        sb.AppendLine("# Skill field, not auto-enforced. Do not hand-edit; regenerate.");
        sb.AppendLine();

        var failures = new List<string>();
        var ids = new HashSet<string>();
        int count = 0, practices = 0, incantations = 0;

        for (int hi = 0; hi < headers.Count; hi++)
        {
            int at = headers[hi];
            var h3m = H3.Match(lines[at]);
            if (!h3m.Success) continue;                       // only H3 entries
            int to = (hi + 1 < headers.Count) ? headers[hi + 1] : secEnd;

            // Find the descriptor line within the block.
            int descLine = -1; Match desc = Match.Empty;
            for (int i = at + 1; i < to; i++)
            {
                string t = lines[i].Trim();
                if (t.Length == 0) continue;
                var dm = Descriptor.Match(t);
                if (dm.Success) { descLine = i; desc = dm; break; }
                // A field/prose line before any descriptor means this H3 is not
                // an art entry (e.g. "Types of Practice", "Discovering …").
                if (Field.IsMatch(t) || (!t.StartsWith("Level ") && t.Length > 0)) break;
            }
            if (descLine < 0) continue;

            string name = HttpUtility.HtmlDecode(h3m.Groups[1].Value).Trim();
            string rawBlock = string.Join("\n", lines.Skip(at + 1).Take(to - at - 1));

            string level = desc.Groups["lvl"].Value;
            string subtype = Unwrap(desc.Groups["sub"].Value);
            string artType = desc.Groups["art"].Value;       // Practice | Incantation
            string skill = Unwrap(desc.Groups["skill"].Value);

            string costToLearn = "", components = "", time = "", duration = "";
            var prose = new List<string>();
            for (int i = descLine + 1; i < to; i++)
            {
                string raw = lines[i].Trim();
                if (raw.Length == 0 || raw.StartsWith("<figure")) continue;
                var fm = Field.Match(raw);
                if (fm.Success)
                {
                    string lbl = fm.Groups["lbl"].Value.Trim(); string val = Unwrap(fm.Groups["val"].Value);
                    switch (lbl.ToLowerInvariant())
                    {
                        case "cost to learn": costToLearn = val; break;
                        case "components": case "component cost": components = val; break;
                        case "completion time": case "time": time = val; break;
                        case "duration": duration = val; break;
                        default: prose.Add(Unwrap(raw)); break;
                    }
                    continue;
                }
                prose.Add(Unwrap(raw));
            }
            string description = CollapseSpaces(string.Join(" ", prose));

            void Check(string f, string v) { if (v.Length > 0 && !Phase2.TextIsFaithful(v, rawBlock)) failures.Add($"  ✗ {name} / {f}: \"{Short(v)}\""); }
            Check("Cost to Learn", costToLearn); Check("Components", components);
            Check("Completion Time", time); Check("Duration", duration);
            Check("Description", description);

            string id = "ORCUS_ART_" + Slug(name);
            string baseId = id; int n = 2; while (!ids.Add(id)) id = $"{baseId}_{n++}";
            count++;
            if (artType.Equals("Practice", StringComparison.OrdinalIgnoreCase)) practices++; else incantations++;

            sb.AppendLine($"- id: {id}");
            sb.AppendLine($"  name: {Scalar(name)}");
            sb.AppendLine($"  type: Ritual");
            sb.AppendLine($"  source: \"Orcus Original\"");
            sb.AppendLine($"  fields:");
            sb.AppendLine($"    Level: \"{level}\"");
            sb.AppendLine($"    \"Art Type\": {Scalar(artType)}");
            if (subtype.Length > 0) sb.AppendLine($"    Category: {Scalar(subtype)}");
            if (skill.Length > 0) sb.AppendLine($"    Skill: {Scalar(skill)}");
            if (costToLearn.Length > 0) foreach (var l in Phase2.EmitFieldLines("Market Price", costToLearn, 4)) sb.AppendLine(l);
            if (components.Length > 0) foreach (var l in Phase2.EmitFieldLines("Component Cost", components, 4)) sb.AppendLine(l);
            if (time.Length > 0) foreach (var l in Phase2.EmitFieldLines("Time", time, 4)) sb.AppendLine(l);
            if (duration.Length > 0) foreach (var l in Phase2.EmitFieldLines("Duration", duration, 4)) sb.AppendLine(l);
            if (description.Length > 0) foreach (var l in Phase2.EmitFieldLines("Description", description, 4)) sb.AppendLine(l);
            sb.AppendLine();
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine($"Wrote {outPath}: {count} arts ({practices} practices, {incantations} incantations).");
        if (failures.Count > 0) { Console.WriteLine($"\nFAILURES ({failures.Count}):"); failures.ForEach(Console.WriteLine); return 2; }
        Console.WriteLine("All art prose passed the verbatim gate.");
        return 0;
    }

    static string Slug(string s)
    {
        var sb = new StringBuilder(); bool u = true;
        foreach (var ch in s.ToUpperInvariant()) { if (char.IsLetterOrDigit(ch)) { sb.Append(ch); u = false; } else if (!u) { sb.Append('_'); u = true; } }
        return sb.ToString().Trim('_');
    }
    static string Scalar(string v) => v.Contains('"') ? $"\"{v.Replace("\"", "\\\"")}\"" : $"\"{v}\"";
    static string Unwrap(string s) => CollapseSpaces(s.Replace("**", "").Replace("*", "").Trim());
    static string CollapseSpaces(string s) => string.Join(' ', s.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries)).Trim();
    static string Short(string s) => s.Length > 90 ? s[..90] + "…" : s;
}
