using System.Text;
using System.Text.RegularExpressions;
using System.Web;

namespace CharM.Orcus.Import;

/// <summary>
/// Deterministic parser + generator for the Advanced Options "# Backgrounds"
/// table (an optional creation rule). Each row becomes a <c>Background</c>
/// element recording its Associated Skills. The background benefit itself is a
/// universal player choice (learn a related language / add an associated skill to
/// your class skills / +2 to an associated skill), so it is captured as a shared
/// Benefit note rather than auto-applied. Names/skills are verbatim from the
/// table; round-trip checked.
/// </summary>
public static class BackgroundGen
{
    static readonly Regex H1 = new(@"^#\s+(.+?)\s*$", RegexOptions.Compiled);
    static readonly Regex Row = new(@"^\|(.+)\|\s*$", RegexOptions.Compiled);

    const string Benefit =
        "When you select a background, you can select one of the following benefits "
        + "(unless another option is specified in the background): 1. You learn a new "
        + "language that the GM agrees seems related to that background. 2. You add one "
        + "of the skills associated with the background to your list of class skills. "
        + "3. You get a +2 bonus to one of the skills associated with the background.";

    public static int Generate(string book, string outPath)
    {
        var lines = File.ReadAllLines(book);
        int secStart = -1, secEnd = lines.Length;
        for (int i = 0; i < lines.Length; i++)
        {
            var m = H1.Match(lines[i]);
            if (!m.Success) continue;
            string h = HttpUtility.HtmlDecode(m.Groups[1].Value).Trim();
            if (secStart < 0) { if (h.Equals("Backgrounds", StringComparison.OrdinalIgnoreCase)) secStart = i; }
            else { secEnd = i; break; }
        }
        if (secStart < 0) throw new Exception("'# Backgrounds' section not found");

        // Find the table header row ("| Name | Associated Skills |").
        int header = -1;
        for (int i = secStart + 1; i < secEnd; i++)
            if (lines[i].TrimStart().StartsWith("|") && lines[i].Contains("Associated Skills")) { header = i; break; }
        if (header < 0) throw new Exception("Backgrounds table not found");

        var sb = new StringBuilder();
        sb.AppendLine("# Backgrounds (Orcus Advanced Options) — an optional creation rule. Generated by");
        sb.AppendLine("# tools/CharM.Orcus.Import (generate-backgrounds). Each row is a Background with");
        sb.AppendLine("# its Associated Skills (verbatim). The benefit is a universal player choice");
        sb.AppendLine("# (related language / add a class skill / +2 to an associated skill), recorded in");
        sb.AppendLine("# the Benefit field rather than auto-applied. Do not hand-edit; regenerate.");
        sb.AppendLine();

        var failures = new List<string>();
        var ids = new HashSet<string>();
        int count = 0;
        for (int i = header + 2; i < secEnd; i++)   // +2 skips header + separator
        {
            var m = Row.Match(lines[i].Trim());
            if (!m.Success) break;
            var cells = m.Groups[1].Value.Split('|').Select(c => Clean(c)).ToArray();
            if (cells.Length < 2 || cells[0].Length == 0 || cells.All(c => c.All(ch => ch == '-'))) continue;
            string name = cells[0], skills = cells[1];
            if (name.Equals("Name", StringComparison.OrdinalIgnoreCase)) continue;

            string rowRaw = string.Join(" ", cells);
            if (!Phase2.TextIsFaithful(skills, rowRaw)) failures.Add($"  ✗ {name}: skills \"{skills}\"");

            string id = "ORCUS_BACKGROUND_" + Slug(name);
            string baseId = id; int n = 2; while (!ids.Add(id)) id = $"{baseId}_{n++}";
            count++;

            sb.AppendLine($"- id: {id}");
            sb.AppendLine($"  name: {Scalar(name)}");
            sb.AppendLine($"  type: Background");
            sb.AppendLine($"  source: \"Orcus Original\"");
            sb.AppendLine($"  fields:");
            sb.AppendLine($"    \"Associated Skills\": {Scalar(skills)}");
            foreach (var l in Phase2.EmitFieldLines("Benefit", Benefit, 4)) sb.AppendLine(l);
            sb.AppendLine();
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine($"Wrote {outPath}: {count} backgrounds.");
        if (failures.Count > 0) { Console.WriteLine($"\nFAILURES ({failures.Count}):"); failures.ForEach(Console.WriteLine); return 2; }
        Console.WriteLine("All background skills verbatim against the table.");
        return 0;
    }

    static string Slug(string s)
    {
        var sb = new StringBuilder(); bool u = true;
        foreach (var ch in s.ToUpperInvariant()) { if (char.IsLetterOrDigit(ch)) { sb.Append(ch); u = false; } else if (!u) { sb.Append('_'); u = true; } }
        return sb.ToString().Trim('_');
    }
    static string Clean(string s) => string.Join(' ', s.Replace("**", "").Replace("*", "")
        .Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries)).Trim();
    static string Scalar(string v) => v.Contains('"') ? $"\"{v.Replace("\"", "\\\"")}\"" : $"\"{v}\"";
}
