using System.Text;
using System.Text.RegularExpressions;
using System.Web;

namespace CharM.Orcus.Import;

/// <summary>
/// Deterministic parser + generator + verbatim gate for the Player Options
/// "# Deities" section — the named setting gods a character may worship. Each
/// becomes a <c>Deity</c> element with its Title, Symbol, Portfolio and Favored
/// Weapon plus the verbatim lore Description. (The four mechanical "God of …"
/// domain deities tied to the Worships kits stay in deities.yaml.)
/// </summary>
public static class DeityGen
{
    static readonly Regex H1 = new(@"^#\s+(.+?)\s*$", RegexOptions.Compiled);
    static readonly Regex H3 = new(@"^###\s+(.+?)\s*$", RegexOptions.Compiled);
    static readonly Regex Field = new(@"^\*\*(?<lbl>[^*:]+?):\*\*\s*(?<val>.*)$", RegexOptions.Compiled);

    public static int Generate(string book, string outPath)
    {
        var lines = File.ReadAllLines(book);
        int secStart = -1, secEnd = lines.Length;
        for (int i = 0; i < lines.Length; i++)
        {
            var m = H1.Match(lines[i]);
            if (!m.Success) continue;
            string h = HttpUtility.HtmlDecode(m.Groups[1].Value).Trim();
            if (secStart < 0) { if (h.Equals("Deities", StringComparison.OrdinalIgnoreCase)) secStart = i; }
            else { secEnd = i; break; }
        }
        if (secStart < 0) throw new Exception("'# Deities' section not found");

        var h3s = new List<int>();
        for (int i = secStart + 1; i < secEnd; i++) if (H3.IsMatch(lines[i])) h3s.Add(i);

        var sb = new StringBuilder();
        sb.AppendLine("# Named deities (Orcus Player Options, # Deities) — the setting gods of the");
        sb.AppendLine("# Outlaw Kingdoms a character may worship. Generated by tools/CharM.Orcus.Import");
        sb.AppendLine("# (generate-deities); Title/Symbol/Portfolio/Favored Weapon + lore are verbatim");
        sb.AppendLine("# & round-trip checked. The four mechanical \"God of …\" domain deities tied to");
        sb.AppendLine("# the Worships kits are in deities.yaml. Do not hand-edit; regenerate.");
        sb.AppendLine();

        var failures = new List<string>();
        var ids = new HashSet<string>();
        int count = 0;
        for (int k = 0; k < h3s.Count; k++)
        {
            int from = h3s[k], to = (k + 1 < h3s.Count) ? h3s[k + 1] : secEnd;
            string name = HttpUtility.HtmlDecode(H3.Match(lines[from]).Groups[1].Value).Trim();
            string rawBlock = string.Join("\n", lines.Skip(from + 1).Take(to - from - 1));

            string title = "", symbol = "", portfolio = "", weapon = "";
            var prose = new List<string>();
            for (int i = from + 1; i < to; i++)
            {
                string raw = lines[i].Trim();
                if (raw.Length == 0 || raw.StartsWith("<figure")) continue;
                var fm = Field.Match(raw);
                if (fm.Success)
                {
                    string lbl = fm.Groups["lbl"].Value.Trim(); string val = Unwrap(fm.Groups["val"].Value);
                    switch (lbl.ToLowerInvariant())
                    {
                        case "symbol": symbol = val; break;
                        case "portfolio": portfolio = val; break;
                        case "favored weapon": weapon = val; break;
                        default: prose.Add(Unwrap(raw)); break;
                    }
                    continue;
                }
                // The first plain line is the epithet/title (e.g. "The Glutton").
                if (title.Length == 0 && prose.Count == 0) title = Unwrap(raw);
                else prose.Add(Unwrap(raw));
            }
            string description = CollapseSpaces(string.Join(" ", prose));

            void Check(string f, string v) { if (v.Length > 0 && !Phase2.TextIsFaithful(v, rawBlock)) failures.Add($"  ✗ {name} / {f}: \"{Short(v)}\""); }
            Check("Title", title); Check("Symbol", symbol); Check("Portfolio", portfolio);
            Check("Favored Weapon", weapon); Check("Description", description);

            string id = "ORCUS_DEITY_" + Slug(name);
            string baseId = id; int n = 2; while (!ids.Add(id)) id = $"{baseId}_{n++}";
            count++;

            sb.AppendLine($"- id: {id}");
            sb.AppendLine($"  name: {Scalar(name)}");
            sb.AppendLine($"  type: Deity");
            sb.AppendLine($"  source: \"Orcus Original\"");
            sb.AppendLine($"  fields:");
            if (title.Length > 0) sb.AppendLine($"    Title: {Scalar(title)}");
            if (symbol.Length > 0) sb.AppendLine($"    Symbol: {Scalar(symbol)}");
            if (portfolio.Length > 0) sb.AppendLine($"    Portfolio: {Scalar(portfolio)}");
            if (weapon.Length > 0) sb.AppendLine($"    \"Favored Weapon\": {Scalar(weapon)}");
            if (description.Length > 0) foreach (var l in Phase2.EmitFieldLines("Description", description, 4)) sb.AppendLine(l);
            sb.AppendLine();
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine($"Wrote {outPath}: {count} named deities.");
        if (failures.Count > 0) { Console.WriteLine($"\nFAILURES ({failures.Count}):"); failures.ForEach(Console.WriteLine); return 2; }
        Console.WriteLine("All deity prose passed the verbatim gate.");
        return 0;
    }

    static string Slug(string s)
    {
        var sb = new StringBuilder(); bool u = true;
        foreach (var ch in s.ToUpperInvariant()) { if (char.IsLetterOrDigit(ch)) { sb.Append(ch); u = false; } else if (!u) { sb.Append('_'); u = true; } }
        return sb.ToString().Trim('_');
    }
    static string Scalar(string v) => v.Contains('"') ? $"\"{v.Replace("\"", "\\\"")}\"" : $"\"{v}\"";
    static string Unwrap(string s) => CollapseSpaces(s.Replace("**", "").Replace("*", "").Trim());
    static string CollapseSpaces(string s) => string.Join(' ', s.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries)).Trim();
    static string Short(string s) => s.Length > 90 ? s[..90] + "…" : s;
}
