using System.Text;
using System.Text.RegularExpressions;
using System.Web;

namespace CharM.Orcus.Import;

/// <summary>
/// Deterministic parser + generator + verbatim gate for the Binds Familiar
/// kit's familiar table. Familiars are mechanically unlike animal companions:
/// they have no stat block of their own (they use the master's defenses, and
/// their max HP is the master's recovery value), so each is modelled the way the
/// engine expects a familiar — a <c>Power</c> named <c>"Familiar: X"</c> carrying
/// <c>Senses</c>, <c>Speed</c>/<c>Secondary Speed</c>, a <c>Constant Benefits</c>
/// rider, and the <c>While Called</c> ability — tagged <c>ORCUS_FAMILIAR</c> for
/// the Binds Familiar select. The two prose columns are copied verbatim and
/// round-trip checked against their table row.
/// </summary>
public static class FamiliarGen
{
    static readonly Regex Row = new(@"^\|(.+)\|\s*$", RegexOptions.Compiled);

    public static int Generate(string book, string outPath)
    {
        var lines = File.ReadAllLines(book);

        // Find the familiar table: header row containing "While Called".
        int header = -1;
        for (int i = 0; i < lines.Length; i++)
            if (lines[i].Contains("While Called") && lines[i].TrimStart().StartsWith("|")) { header = i; break; }
        if (header < 0) throw new Exception("familiar table (\"While Called\") not found");

        var rows = new List<string[]>();
        for (int i = header + 2; i < lines.Length; i++)   // +2 skips header + separator
        {
            var m = Row.Match(lines[i].Trim());
            if (!m.Success) break;
            var cells = m.Groups[1].Value.Split('|').Select(c => c.Trim()).ToArray();
            if (cells.Length < 5 || cells.All(c => c.Length == 0 || c.All(ch => ch == '-'))) break;
            rows.Add(cells);
        }

        var sb = new StringBuilder();
        sb.AppendLine("# Familiars (Orcus Classes and Powers, Binds Familiar kit) — generated by");
        sb.AppendLine("# tools/CharM.Orcus.Import (generate-familiars) from the familiar table. Each is");
        sb.AppendLine("# a \"Familiar: X\" Power (the engine's familiar shape: no own stat block — it");
        sb.AppendLine("# uses your defenses, max HP = your recovery value), tagged ORCUS_FAMILIAR for");
        sb.AppendLine("# the Binds Familiar select. Senses/Speed are structural; the Constant Benefits");
        sb.AppendLine("# and While Called columns are verbatim. Do not hand-edit; regenerate.");
        sb.AppendLine();

        var ids = new HashSet<string>();
        var failures = new List<string>();
        int count = 0;
        foreach (var c in rows)
        {
            string name = Clean(c[0]);
            string senses = Clean(c[1]);
            string speedRaw = Clean(c[2]);
            string constant = Clean(c[3]);
            string whileCalled = Clean(c[4]);
            if (name.Length == 0) continue;
            count++;

            string rowRaw = string.Join(" ", c);
            void Check(string f, string v) { if (v.Length > 0 && !Phase2.TextIsFaithful(v, rowRaw)) failures.Add($"  ✗ {name} / {f}: \"{Short(v)}\""); }
            Check("Constant Benefits", constant);
            Check("While Called", whileCalled);

            // Speed: split a leading walk value from extra modes (fly/swim/climb).
            string speed = speedRaw, secondary = "";
            int comma = speedRaw.IndexOf(',');
            if (comma > 0) { speed = speedRaw[..comma].Trim(); secondary = speedRaw[(comma + 1)..].Trim(); }

            string id = "ORCUS_FAMILIAR_" + Slug(name);
            string baseId = id; int n = 2; while (!ids.Add(id)) id = $"{baseId}_{n++}";

            sb.AppendLine($"- id: {id}");
            sb.AppendLine($"  name: {Scalar("Familiar: " + name)}");
            sb.AppendLine($"  type: Power");
            sb.AppendLine($"  source: \"Orcus Original\"");
            sb.AppendLine($"  categories: [ORCUS_FAMILIAR]");
            sb.AppendLine($"  fields:");
            sb.AppendLine($"    Size: Tiny");
            if (senses.Length > 0) sb.AppendLine($"    Senses: {Scalar(senses)}");
            if (speed.Length > 0) sb.AppendLine($"    Speed: {Scalar(speed)}");
            if (secondary.Length > 0) sb.AppendLine($"    \"Secondary Speed\": {Scalar(secondary)}");
            if (constant.Length > 0) foreach (var l in Phase2.EmitFieldLines("Constant Benefits", constant, 4)) sb.AppendLine(l);
            if (whileCalled.Length > 0) foreach (var l in Phase2.EmitFieldLines("While Called", whileCalled, 4)) sb.AppendLine(l);
            sb.AppendLine();
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine($"Wrote {outPath}: {count} familiars.");

        if (failures.Count > 0)
        {
            Console.WriteLine($"\nFAILURES ({failures.Count}) — text not verbatim in its table row:");
            failures.ForEach(Console.WriteLine);
            return 2;
        }
        Console.WriteLine("All familiar Constant Benefits / While Called text passed the verbatim gate.");
        return 0;
    }

    static string Slug(string s)
    {
        var sb = new StringBuilder(); bool u = true;
        foreach (var ch in s.ToUpperInvariant()) { if (char.IsLetterOrDigit(ch)) { sb.Append(ch); u = false; } else if (!u) { sb.Append('_'); u = true; } }
        return sb.ToString().Trim('_');
    }
    static string Clean(string s) => string.Join(' ', s.Replace("**", "").Replace("*", "").Replace("`", "")
        .Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries)).Trim();
    static string Scalar(string v) => v.Contains('"') ? $"\"{v.Replace("\"", "\\\"")}\"" : $"\"{v}\"";
    static string Short(string s) => s.Length > 90 ? s[..90] + "…" : s;
}
