using System.Text;
using System.Text.RegularExpressions;
using System.Web;

namespace CharM.Orcus.Import;

/// <summary>
/// Deterministic generator + verbatim gate for the player-facing optional rules
/// ("Variant: …" / "Rules Variant: …" / "Variant Rule: …" sections) scattered
/// across the Orcus books. Each becomes a toggleable <c>Variant</c> element whose
/// verbatim intro prose is its Description, so the app's Campaign Settings panel
/// lists it as an on/off campaign option (the engine applies a toggled-on
/// element's own rules and lets other content gate on it via <c>requires</c>).
///
/// The set is curated (monster-building "Variants" and similar GM-only material
/// are excluded). Where a variant has a clean build-time hook it carries
/// mechanical rules via <see cref="RulesOverlay"/> — e.g. Bonus Feats grants
/// Keen Defenses and a Weapon Focus / Focused Caster pick at level 11.
/// (The "Feats and Kits" House Rule already lives in kits.yaml and is surfaced
/// by the same data-driven panel.)
/// </summary>
public static class VariantGen
{
    static readonly Regex AnyHeader = new(@"^\s*(#{1,6}\s|<h\d|<figure|>|\||\*\*[^*]+:\*\*|[-*]\s)", RegexOptions.Compiled);

    sealed record Spec(string BookGlob, string Header, string Id, string Name);

    static readonly Spec[] Specs =
    [
        new("Orcus Advanced Options*.md", "### Variant: True Grit",
            "ORCUS_VARIANT_TRUE_GRIT", "True Grit"),
        new("Orcus Player Options*.md", "## Variant: Bonus Feats",
            "ORCUS_VARIANT_BONUS_FEATS", "Bonus Feats"),
        new("Orcus Advanced Options*.md", "## Rules Variant: Gated Arts",
            "ORCUS_VARIANT_GATED_ARTS", "Gated Arts"),
        new("Orcus Rulebook*.md", "### Variant: Skills with Different Abilities",
            "ORCUS_VARIANT_SKILLS_DIFFERENT_ABILITIES", "Skills with Different Abilities"),
        new("Orcus Rulebook*.md", "### Variant: Nine-Point Alignment",
            "ORCUS_VARIANT_NINE_POINT_ALIGNMENT", "Nine-Point Alignment"),
        new("Orcus Rulebook*.md", "##### Variant: No Weapon Limitations for Small Characters",
            "ORCUS_VARIANT_NO_SMALL_WEAPON_LIMITS", "No Weapon Limitations for Small Characters"),
        new("Orcus Rulebook*.md", "### Variant Rule: One Free Action per Turn",
            "ORCUS_VARIANT_ONE_FREE_ACTION", "One Free Action per Turn"),
        new("Orcus Rulebook*.md", "### Variant: No Negative HP",
            "ORCUS_VARIANT_NO_NEGATIVE_HP", "No Negative HP"),
    ];

    // Mechanical effects applied when the variant is toggled on (the engine runs
    // a free-granted element's own Phase-1 rules). Keyed by element id.
    static readonly Dictionary<string, string[]> RulesOverlay = new()
    {
        // "all characters [get] the Keen Defenses feat and either the Weapon Focus
        // or Focus[ed] Caster feats for free … from level 11 onwards."
        ["ORCUS_VARIANT_BONUS_FEATS"] =
        [
            "{ grant: ORCUS_FEAT_KEEN_DEFENSES, type: Feat, level: 11 }",
            "{ select: { type: Feat, number: 1, category: ORCUS_BONUS_FEAT_CHOICE, name: \"Bonus Feat (Weapon Focus or Focused Caster)\", level: 11 } }",
        ],
    };

    public static int Generate(string root, string outPath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Optional rules / variants (Orcus) — generated by tools/CharM.Orcus.Import");
        sb.AppendLine("# (generate-variants). Each is a toggleable Variant element: the app's Campaign");
        sb.AppendLine("# Settings panel lists every House Rule / Variant as an on/off option, and the");
        sb.AppendLine("# engine applies a toggled-on element's own rules / lets content gate on it via");
        sb.AppendLine("# requires. Intro prose is the verbatim Description (round-trip checked). Bonus");
        sb.AppendLine("# Feats carries build rules (Keen Defenses + a Weapon Focus / Focused Caster");
        sb.AppendLine("# pick at level 11). The \"Feats and Kits\" House Rule lives in kits.yaml. Do not");
        sb.AppendLine("# hand-edit; regenerate.");
        sb.AppendLine();

        var failures = new List<string>();
        int count = 0;
        foreach (var spec in Specs)
        {
            string book = Directory.EnumerateFiles(root, spec.BookGlob).Single();
            var lines = File.ReadAllLines(book);

            int at = -1;
            for (int i = 0; i < lines.Length; i++)
                if (lines[i].TrimEnd().Equals(spec.Header, StringComparison.Ordinal)) { at = i; break; }
            if (at < 0) { failures.Add($"  ✗ {spec.Name}: header not found ({spec.Header})"); continue; }

            // Description = the intro paragraphs after the header, up to the next
            // header / HTML / blockquote / table / bold label / bullet line.
            var prose = new List<string>();
            int raw0 = at + 1;
            for (int i = at + 1; i < lines.Length; i++)
            {
                string raw = lines[i].Trim();
                if (raw.Length == 0) continue;          // span blank lines between intro paragraphs
                if (AnyHeader.IsMatch(lines[i])) break;
                prose.Add(Unwrap(raw));
            }
            string rawBlock = string.Join("\n", lines.Skip(raw0).Take(40));
            string description = CollapseSpaces(string.Join(" ", prose));
            if (description.Length == 0) { failures.Add($"  ✗ {spec.Name}: no prose captured"); continue; }
            if (!Phase2.TextIsFaithful(description, rawBlock))
                failures.Add($"  ✗ {spec.Name}: description not verbatim \"{Short(description)}\"");

            count++;
            sb.AppendLine($"- id: {spec.Id}");
            sb.AppendLine($"  name: {Scalar(spec.Name)}");
            sb.AppendLine($"  type: Variant");
            sb.AppendLine($"  source: \"Orcus Original\"");
            sb.AppendLine($"  fields:");
            foreach (var l in Phase2.EmitFieldLines("Description", description, 4)) sb.AppendLine(l);
            if (RulesOverlay.TryGetValue(spec.Id, out var rules))
            {
                sb.AppendLine($"  rules:");
                foreach (var r in rules) sb.AppendLine($"    - {r}");
            }
            sb.AppendLine();
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine($"Wrote {outPath}: {count} variants.");
        if (failures.Count > 0) { Console.WriteLine($"\nFAILURES ({failures.Count}):"); failures.ForEach(Console.WriteLine); return 2; }
        Console.WriteLine("All variant prose passed the verbatim gate.");
        return 0;
    }

    static string Scalar(string v) => v.Contains('"') ? $"\"{v.Replace("\"", "\\\"")}\"" : $"\"{v}\"";
    static string Unwrap(string s) => CollapseSpaces(s.Replace("**", "").Replace("*", "").Trim());
    static string CollapseSpaces(string s) => string.Join(' ', s.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries)).Trim();
    static string Short(string s) => s.Length > 90 ? s[..90] + "…" : s;
}
