using System.Text;
using System.Text.RegularExpressions;
using System.Web;

namespace CharM.Orcus.Import;

/// <summary>
/// Deterministic parser + generator + verbatim gate for the Advanced Options
/// "# Vehicles" section. Each vehicle is a <c>Vehicle</c> element: structured
/// stats (Item Level, Size, Capacity, Cargo, HP, defenses, Resistance) plus the
/// verbatim Speed / Driver Skill / Description and any named ability (Careen, …),
/// round-trip checked against the vehicle's own source block.
/// </summary>
public static class VehicleGen
{
    static readonly Regex H1 = new(@"^#\s+(.+?)\s*$", RegexOptions.Compiled);
    static readonly Regex H3 = new(@"^###\s+(.+?)\s*$", RegexOptions.Compiled);
    static readonly Regex LevelLine = new(@"^\*\*Level\s+(?<lvl>\d+)\s+(?<size>\w+)\s+vehicle\*\*\s*$", RegexOptions.Compiled);
    // A "**Label:** value" or "**Label** value" segment.
    static readonly Regex Field = new(@"^\*\*(?<lbl>[^*:]+?):?\*\*\s*(?<val>.*)$", RegexOptions.Compiled);

    static readonly Dictionary<string, string> Rename = new(StringComparer.OrdinalIgnoreCase)
    {
        ["AC"] = "Armor Class", ["Fortitude"] = "Fortitude Defense",
        ["Reflex"] = "Reflex Defense", ["Will"] = "Will Defense",
    };
    // Stat labels that appear inline on the multi-field Capacity/HP lines.
    static readonly HashSet<string> StatLabels = new(StringComparer.OrdinalIgnoreCase)
    { "Capacity", "Cargo", "HP", "AC", "Fortitude", "Reflex", "Will", "Resistance" };

    public static int Generate(string book, string outPath)
    {
        var lines = File.ReadAllLines(book);
        int secStart = -1, secEnd = lines.Length;
        for (int i = 0; i < lines.Length; i++)
        {
            var m = H1.Match(lines[i]);
            if (!m.Success) continue;
            string h = HttpUtility.HtmlDecode(m.Groups[1].Value).Trim();
            if (secStart < 0) { if (h.Equals("Vehicles", StringComparison.OrdinalIgnoreCase)) secStart = i; }
            else { secEnd = i; break; }
        }
        if (secStart < 0) throw new Exception("'# Vehicles' section not found");

        var h3s = new List<int>();
        for (int i = secStart + 1; i < secEnd; i++) if (H3.IsMatch(lines[i])) h3s.Add(i);

        var sb = new StringBuilder();
        sb.AppendLine("# Vehicles (Orcus Advanced Options) — generated by tools/CharM.Orcus.Import");
        sb.AppendLine("# (generate-vehicles). Structured stats (level/size/capacity/cargo/HP/defenses/");
        sb.AppendLine("# resistance) plus verbatim Speed / Driver Skill / Description and named");
        sb.AppendLine("# abilities (Careen, …). Do not hand-edit; regenerate instead.");
        sb.AppendLine();

        var failures = new List<string>();
        var ids = new HashSet<string>();
        int count = 0;
        for (int k = 0; k < h3s.Count; k++)
        {
            int from = h3s[k], to = (k + 1 < h3s.Count) ? h3s[k + 1] : secEnd;
            string name = HttpUtility.HtmlDecode(H3.Match(lines[from]).Groups[1].Value).Trim();
            string rawBlock = string.Join("\n", lines.Skip(from + 1).Take(to - from - 1));

            string itemLevel = "", size = "";
            var stats = new List<(string K, string V)>();   // ordered fields
            var prose = new List<string>();                  // description paragraphs

            for (int i = from + 1; i < to; i++)
            {
                string raw = lines[i].Trim();
                if (raw.Length == 0 || raw.StartsWith("<figure")) continue;

                var lm = LevelLine.Match(raw);
                if (lm.Success) { itemLevel = lm.Groups["lvl"].Value; size = lm.Groups["size"].Value; continue; }

                if (raw.StartsWith("**"))
                {
                    // One or more "**Label:** value" segments separated by ';'.
                    foreach (var seg in raw.Split(';', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries))
                    {
                        var fm = Field.Match(seg.Trim());
                        if (!fm.Success) { prose.Add(Unwrap(seg)); continue; }
                        string lbl = fm.Groups["lbl"].Value.Trim();
                        string val = fm.Groups["val"].Value.Trim();
                        // The "AC 15, Fortitude 17" segment packs a second label
                        // after a comma. Only split when an embedded **label** is
                        // present — not on a thousands-separator (e.g. "2,000").
                        if (val.Contains("**"))
                        {
                            SplitInlineDefenses(lbl, val, stats);
                            continue;
                        }
                        stats.Add((Rename.GetValueOrDefault(lbl, lbl), Unwrap(val)));
                    }
                    continue;
                }
                prose.Add(Unwrap(raw));
            }

            string id = "ORCUS_VEHICLE_" + Slug(name);
            string baseId = id; int n = 2; while (!ids.Add(id)) id = $"{baseId}_{n++}";
            count++;

            // Verbatim gate on prose-bearing fields + description.
            void Check(string f, string v) { if (v.Length > 0 && !Phase2.TextIsFaithful(v, rawBlock)) failures.Add($"  ✗ {name} / {f}: \"{Short(v)}\""); }
            string description = CollapseSpaces(string.Join(" ", prose));
            Check("Description", description);
            foreach (var (kk, vv) in stats) Check(kk, vv);

            sb.AppendLine($"- id: {id}");
            sb.AppendLine($"  name: {Scalar(name)}");
            sb.AppendLine($"  type: Vehicle");
            sb.AppendLine($"  source: \"Orcus Original\"");
            sb.AppendLine($"  fields:");
            if (itemLevel.Length > 0) sb.AppendLine($"    \"Item Level\": \"{itemLevel}\"");
            if (size.Length > 0) sb.AppendLine($"    Size: {Scalar(size)}");
            foreach (var (kk, vv) in stats)
                if (vv.Length > 0) foreach (var l in Phase2.EmitFieldLines(kk, vv, 4)) sb.AppendLine(l);
            if (description.Length > 0) foreach (var l in Phase2.EmitFieldLines("Description", description, 4)) sb.AppendLine(l);
            sb.AppendLine();
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine($"Wrote {outPath}: {count} vehicles.");
        if (failures.Count > 0) { Console.WriteLine($"\nFAILURES ({failures.Count}):"); failures.ForEach(Console.WriteLine); return 2; }
        Console.WriteLine("All vehicle prose passed the verbatim gate.");
        return 0;
    }

    /// <summary>Parse the "AC 15, Fortitude 17" style remainder where the first
    /// value belongs to <paramref name="firstLabel"/> and subsequent comma parts
    /// are their own "Label value" pairs.</summary>
    static int SplitInlineDefenses(string firstLabel, string val, List<(string, string)> stats)
    {
        var parts = val.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        // First part is the firstLabel's value.
        stats.Add((Rename.GetValueOrDefault(firstLabel, firstLabel), Unwrap(parts[0])));
        for (int i = 1; i < parts.Length; i++)
        {
            var fm = Field.Match(parts[i].Trim());
            if (fm.Success)
                stats.Add((Rename.GetValueOrDefault(fm.Groups["lbl"].Value.Trim(), fm.Groups["lbl"].Value.Trim()), Unwrap(fm.Groups["val"].Value)));
            else
            {
                // "Resistance hardness 5" (no colon) — split on first space.
                string p = Unwrap(parts[i]);
                int sp = p.IndexOf(' ');
                if (sp > 0) stats.Add((p[..sp], p[(sp + 1)..].Trim()));
            }
        }
        return parts.Length;
    }

    static string Slug(string s)
    {
        var sb = new StringBuilder(); bool u = true;
        foreach (var ch in s.ToUpperInvariant()) { if (char.IsLetterOrDigit(ch)) { sb.Append(ch); u = false; } else if (!u) { sb.Append('_'); u = true; } }
        return sb.ToString().Trim('_');
    }
    static string Scalar(string v) => v.Contains('"') ? $"\"{v.Replace("\"", "\\\"")}\"" : $"\"{v}\"";
    static string Unwrap(string s) => CollapseSpaces(s.Replace("**", "").Replace("*", "").Trim());
    static string CollapseSpaces(string s) => string.Join(' ', s.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries)).Trim();
    static string Short(string s) => s.Length > 90 ? s[..90] + "…" : s;
}
